name: Deploy WAR to Tomcat

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  deploy:
    runs-on: windows-latest  # Runs the job on a Windows runner

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up JDK (if required for building WAR)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Upload the .war file (can be built during this job if needed)
    - name: Build WAR file (if applicable)
      run: |
        # Commands to build your WAR file, if needed
        # Example: mvn clean install -DskipTests

    # Upload WAR file to Windows server via SSH/WinRM
    - name: Deploy WAR to Windows Server
      uses: appleboy/ssh-action@v0.1.6  # GitHub Action for SSH deployments
      with:
        host: ${{ secrets.SERVER_HOST }}  # Add your server's IP or hostname
        username: ${{ secrets.SERVER_USERNAME }}  # Username for SSH login
        password: ${{ secrets.SERVER_PASSWORD }}  # Or use an SSH key for authentication
        port: 22  # Default SSH port, or the port your server uses
        script: |
          # Stop Tomcat (if needed)
          stop-service Tomcat9  # Adjust if your Tomcat service is named differently
          
          # Remove previous WAR (optional)
          remove-item "C:\path\to\tomcat\webapps\yourapp.war" -force
          
          # Copy the new WAR to Tomcat's webapps folder
          copy-item "C:\path\to\your\war\file.war" "C:\path\to\tomcat\webapps\yourapp.war" -force
          
          # Start Tomcat again
          start-service Tomcat9
          
          # You could also restart Tomcat if needed
          # Restart-Service Tomcat9
          
          Write-Host "Deployment Complete"
      
    # Optional: Verify that deployment is successful (HTTP check)
    - name: Verify Deployment
      run: |
        curl --head http://yourserver.local:8080/yourapp
        # You can add additional logic to verify if the application is running.
